package presentacion;

import model.Departamento;
import model.Empleado;
import model.Inventario;
import dao.impl.Conexion;
import dao.impl.DepartamentoDAOImpl;
import dao.impl.EmpleadoDAOImpl;
import dao.impl.InventarioDAOImpl;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author James
 */
public class DAgregarInventario extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DAgregarInventario.class.getName());

    /**
     * Creates new form DAgregarEmpleado
     */
    private Conexion conexionDB;
    private Dashboard dashboard;
    private int idInventario = -1;

    public DAgregarInventario(Dashboard parent, boolean modal, Conexion conexionDB) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
        this.dashboard = parent;
        this.conexionDB = conexionDB;
    }

    // Constructor para editar
    public DAgregarInventario(Dashboard parent, boolean modal, Conexion conexionDB, Inventario inventario) {
        this(parent, modal, conexionDB); // reutiliza el otro constructor
        this.idInventario = inventario.getIdItem();

        // Prellenar los campos
        txt_nombre.setText(inventario.getNombreItem());
        txt_stock_actual.setText(String.valueOf(inventario.getStockActual()));
        txt_unidad.setText(inventario.getUnidad());
        txt_ubicacion.setText(inventario.getUbicacion());
        txt_stock_minimo.setText(String.valueOf(inventario.getStockMinimo()));
        txt_precio_unitario.setText(String.valueOf(inventario.getPrecioUnitario()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIniciarSes = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txt_ubicacion = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        lblCorreo1 = new javax.swing.JLabel();
        txt_stock_actual = new javax.swing.JTextField();
        lblCorreo2 = new javax.swing.JLabel();
        txt_unidad = new javax.swing.JTextField();
        btnLogin3 = new javax.swing.JButton();
        lblCorreo4 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        lblCorreo5 = new javax.swing.JLabel();
        txt_precio_unitario = new javax.swing.JTextField();
        lblCorreo6 = new javax.swing.JLabel();
        txt_stock_minimo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSes.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblIniciarSes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIniciarSes.setText("Agregar Producto");
        lblIniciarSes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblIniciarSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 778, -1));

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo.setText("Nombre");
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 340, 39));

        txt_ubicacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_ubicacion.setForeground(new java.awt.Color(27, 55, 79));
        txt_ubicacion.setCaretColor(new java.awt.Color(27, 55, 79));
        txt_ubicacion.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jPanel1.add(txt_ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 338, 43));

        btnAgregarProducto.setBackground(new java.awt.Color(0, 121, 216));
        btnAgregarProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 470, 230, 60));

        lblCorreo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo1.setText("Stock actual");
        jPanel1.add(lblCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 338, 39));

        txt_stock_actual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_stock_actual.setForeground(new java.awt.Color(27, 55, 79));
        txt_stock_actual.setCaretColor(new java.awt.Color(27, 55, 79));
        txt_stock_actual.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jPanel1.add(txt_stock_actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 338, 43));

        lblCorreo2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo2.setText("Unidad");
        jPanel1.add(lblCorreo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 338, 39));

        txt_unidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_unidad.setForeground(new java.awt.Color(27, 55, 79));
        txt_unidad.setCaretColor(new java.awt.Color(27, 55, 79));
        txt_unidad.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jPanel1.add(txt_unidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 338, 43));

        btnLogin3.setBackground(new java.awt.Color(255, 102, 102));
        btnLogin3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogin3.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin3.setText("Cancelar");
        btnLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 180, 60));

        lblCorreo4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo4.setText("Ubicacion");
        jPanel1.add(lblCorreo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 184, 39));

        txt_nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(27, 55, 79));
        txt_nombre.setCaretColor(new java.awt.Color(27, 55, 79));
        txt_nombre.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 338, 43));

        lblCorreo5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo5.setText("Stock minimo");
        jPanel1.add(lblCorreo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 184, 39));

        txt_precio_unitario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_precio_unitario.setForeground(new java.awt.Color(27, 55, 79));
        txt_precio_unitario.setCaretColor(new java.awt.Color(27, 55, 79));
        txt_precio_unitario.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jPanel1.add(txt_precio_unitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 338, 43));

        lblCorreo6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo6.setText("Precio unitario");
        jPanel1.add(lblCorreo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 184, 39));

        txt_stock_minimo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_stock_minimo.setForeground(new java.awt.Color(27, 55, 79));
        txt_stock_minimo.setCaretColor(new java.awt.Color(27, 55, 79));
        txt_stock_minimo.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jPanel1.add(txt_stock_minimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 338, 43));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 790, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        String nombre = txt_nombre.getText().trim();
        int stock_actual = Integer.parseInt(txt_stock_actual.getText().trim());
        String unidad = txt_unidad.getText().trim();
        String ubicacion = txt_ubicacion.getText().trim();
        int stock_minimo = Integer.parseInt(txt_stock_minimo.getText().trim());
        double precio_unitario = Double.parseDouble(txt_precio_unitario.getText().trim());

        Inventario inventario = new Inventario(
                idInventario, // pasa el ID si es edición
                nombre,
                stock_actual,
                unidad,
                ubicacion,
                stock_minimo,
                precio_unitario
        );

        InventarioDAOImpl inventarioDAO = new InventarioDAOImpl(conexionDB.getConexion());
        try {
            if (idInventario == -1) {
                inventarioDAO.insertar(inventario);
                JOptionPane.showMessageDialog(this, "Inventario agregado con éxito.",
                        "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                inventarioDAO.actualizar(inventario);
                JOptionPane.showMessageDialog(this, "Inventario actualizado con éxito.",
                        "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }

            if (dashboard != null) {
                dashboard.cargarInventarioEnTabla();
            }
            this.dispose();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar el inventario.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnLogin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnLogin3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnLogin3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblCorreo2;
    private javax.swing.JLabel lblCorreo4;
    private javax.swing.JLabel lblCorreo5;
    private javax.swing.JLabel lblCorreo6;
    private javax.swing.JLabel lblIniciarSes;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio_unitario;
    private javax.swing.JTextField txt_stock_actual;
    private javax.swing.JTextField txt_stock_minimo;
    private javax.swing.JTextField txt_ubicacion;
    private javax.swing.JTextField txt_unidad;
    // End of variables declaration//GEN-END:variables
}
