package presentacion;

import model.Departamento;
import model.Empleado;
import dao.impl.Conexion;
import dao.impl.DepartamentoDAOImpl;
import dao.impl.EmpleadoDAOImpl;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import javax.swing.JOptionPane;
import utilidades.GeneradorReporte;

/**
 *
 * @author James
 */
public class DGenerarReporte extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DGenerarReporte.class.getName());

    /**
     * Creates new form DAgregarEmpleado
     */
    private Conexion conexionDB;
    private Dashboard dashboard;

    public DGenerarReporte(Dashboard parent, boolean modal, Conexion conexionDB) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
        this.dashboard = parent;
        this.conexionDB = conexionDB;
        cargarCategorias();
    }

    private void cargarCategorias() {
        cb_categorias.removeAllItems();

        cb_categorias.addItem("Seleccionar...");
        cb_categorias.addItem("Asistencia Mensual");
        cb_categorias.addItem("Distribución por Departamento");
        cb_categorias.addItem("Total de Empleados");
        cb_categorias.addItem("Inventario General");
        cb_categorias.addItem("Stock Actual");
        cb_categorias.addItem("Entradas y Salidas de Inventario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIniciarSes = new javax.swing.JLabel();
        btnAgregarEmpleado = new javax.swing.JButton();
        btnLogin3 = new javax.swing.JButton();
        lblCorreo6 = new javax.swing.JLabel();
        cb_categorias = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSes.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblIniciarSes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIniciarSes.setText("Generar Reporte");
        lblIniciarSes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblIniciarSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 778, -1));

        btnAgregarEmpleado.setBackground(new java.awt.Color(0, 121, 216));
        btnAgregarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarEmpleado.setText("Generar");
        btnAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 230, 60));

        btnLogin3.setBackground(new java.awt.Color(255, 102, 102));
        btnLogin3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogin3.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin3.setText("Cancelar");
        btnLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 180, 60));

        lblCorreo6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo6.setText("Categoria");
        jPanel1.add(lblCorreo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 184, 39));

        cb_categorias.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(cb_categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 690, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 790, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoActionPerformed
        String categoria = (String) cb_categorias.getSelectedItem();
        GeneradorReporte generadorReporte = new GeneradorReporte(conexionDB.getConexion());

        switch (categoria) {
            case "Asistencia Mensual":
                generadorReporte.generarReporte("asistencia_mensual", categoria);
                break;
            case "Distribución por Departamento":
                generadorReporte.generarReporte("empleados_departamento", categoria);
                break;
            case "Total de Empleados":
                generadorReporte.generarReporte("total_empleados", categoria);
                break;
            case "Inventario General":
                generadorReporte.generarReporte("inventario_general", categoria);
                break;
            case "Stock Actual":
                generadorReporte.generarReporte("stock_actual", categoria);
                break;
            case "Entradas y Salidas de Inventario":
                generadorReporte.generarReporte("entrada_salida_inventario", categoria);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Seleccione una categoría válida.");
        }
    }//GEN-LAST:event_btnAgregarEmpleadoActionPerformed

    private void btnLogin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnLogin3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnLogin3;
    private javax.swing.JComboBox<String> cb_categorias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCorreo6;
    private javax.swing.JLabel lblIniciarSes;
    // End of variables declaration//GEN-END:variables
}
