package presentacion;

/**
 *
 * @author James
 */
public class DRecuperarCuenta extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DRecuperarCuenta.class.getName());

    /**
     * Creates new form RecuperarCuenta
     */
    public DRecuperarCuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
        utilidades.Utilidades.setImageLabel(lblLogo, "src/main/java/imagenes/login.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIniciarSes1 = new javax.swing.JLabel();
        lblCorreo1 = new javax.swing.JLabel();
        txtCorreo1 = new javax.swing.JTextField();
        lblContraseña1 = new javax.swing.JLabel();
        btnLogin1 = new javax.swing.JButton();
        lblContraseña2 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(789, 511));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblIniciarSes1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblIniciarSes1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIniciarSes1.setText("Recuperar cuenta");
        lblIniciarSes1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCorreo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo1.setText("Introduce el correo electronico");

        txtCorreo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCorreo1.setForeground(new java.awt.Color(27, 55, 79));
        txtCorreo1.setCaretColor(new java.awt.Color(27, 55, 79));
        txtCorreo1.setMargin(new java.awt.Insets(2, 10, 2, 10));

        lblContraseña1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblContraseña1.setForeground(new java.awt.Color(255, 51, 51));
        lblContraseña1.setText("la contraseña");
        lblContraseña1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContraseña1MouseClicked(evt);
            }
        });

        btnLogin1.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin1.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin1.setText("Continuar");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        lblContraseña2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblContraseña2.setForeground(new java.awt.Color(255, 51, 51));
        lblContraseña2.setText("Se le enviara un correo para restablecer");
        lblContraseña2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContraseña2MouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblIniciarSes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCorreo1)
                        .addComponent(txtCorreo1)
                        .addComponent(lblContraseña1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblContraseña2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIniciarSes1)
                .addGap(50, 50, 50)
                .addComponent(lblCorreo1)
                .addGap(5, 5, 5)
                .addComponent(txtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(lblContraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblContraseña1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContraseña1MouseClicked
       
    }//GEN-LAST:event_lblContraseña1MouseClicked

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
       
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void lblContraseña2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContraseña2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblContraseña2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseña1;
    private javax.swing.JLabel lblContraseña2;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblIniciarSes1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextField txtCorreo1;
    // End of variables declaration//GEN-END:variables
}
