package presentacion;

/**
 *
 * @author James
 */
import clases.Usuario;
import datos.Conexion;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    private Conexion conexionDB;

    public Login(Conexion conexionDB) {
        initComponents();
        this.setLocationRelativeTo(this);
        utilidades.Utilidades.setImageLabel(lblLogo, "src/main/java/imagenes/login.jpg");
        this.conexionDB = conexionDB;

        txtCorreo.setText("12345678");
        txtContraseña.setText("admin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIniciarSes = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblContraseña1 = new javax.swing.JLabel();
        btnLogin1 = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - MTD");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSes.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblIniciarSes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIniciarSes.setText("Iniciar Sesion");
        lblIniciarSes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblIniciarSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 390, -1));

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo.setText("DNI");
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(27, 55, 79));
        txtCorreo.setCaretColor(new java.awt.Color(27, 55, 79));
        txtCorreo.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 390, 43));

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblContraseña.setText("Contraseña:");
        jPanel1.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txtContraseña.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 390, 43));

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Ingresar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 390, 60));

        lblContraseña1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContraseña1.setForeground(new java.awt.Color(255, 51, 51));
        lblContraseña1.setText("Olvidaste la contraseña");
        lblContraseña1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContraseña1MouseClicked(evt);
            }
        });
        jPanel1.add(lblContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 210, -1));

        btnLogin1.setBackground(new java.awt.Color(0, 121, 216));
        btnLogin1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin1.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin1.setText("Ingresar como empleado");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 390, 47));
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 6, 301, 505));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variable global para contar intentos fallidos
    private int intentosFallidos = 0;

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String dni = txtCorreo.getText().trim();
        char[] passwordChars = txtContraseña.getPassword();
        String pass = new String(passwordChars);

        // 1. Validar campos vacíos
        if (dni.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 2. Intentar autenticar
            Usuario usuarioAutenticado = datos.LoginService.autenticarUsuario(conexionDB.getConexion(), dni, pass);
            System.out.println(datos.LoginService.hashearContrasena(pass));

            if (usuarioAutenticado != null) {
                // 3. Verificar rol

                // Accede al panel
                Dashboard d = new Dashboard(usuarioAutenticado, conexionDB);
                d.setVisible(true);
                this.dispose();

            } else {
                // Credenciales incorrectas
                intentosFallidos++;
                if (intentosFallidos >= 3) {
                    JOptionPane.showMessageDialog(this, "Cuenta bloqueada temporalmente por múltiples intentos fallidos.",
                            "Cuenta bloqueada", JOptionPane.ERROR_MESSAGE);
                    btnLogin.setEnabled(false); // Bloquear botón de login
                } else {
                    JOptionPane.showMessageDialog(this, "DNI o contraseña incorrectos. Intento " + intentosFallidos + " de 3",
                            "Error de Autenticación", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar iniciar sesión.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            System.getLogger(Login.class.getName()).log(System.Logger.Level.ERROR, "Error de login", ex);
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblContraseña1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContraseña1MouseClicked
        DRecuperarCuenta rc = new DRecuperarCuenta(this, true);
        rc.setVisible(true);
    }//GEN-LAST:event_lblContraseña1MouseClicked

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        DEmpleado empleado = new DEmpleado(this, false, conexionDB);
        empleado.setVisible(true);
    }//GEN-LAST:event_btnLogin1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblContraseña1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblIniciarSes;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
