package view;

import model.Departamento;
import model.Empleado;
import dao.impl.Conexion;
import dao.impl.DepartamentoDAOImpl;
import dao.impl.EmpleadoDAOImpl;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author James
 */
public class DAgregarEmpleado extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DAgregarEmpleado.class.getName());

    /**
     * Creates new form DAgregarEmpleado
     */
    private Conexion conexionDB;
    private Dashboard dashboard;
    private Empleado empleadoEditar;

    public DAgregarEmpleado(Dashboard parent, boolean modal, Conexion conexionDB) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
        this.dashboard = parent;
        this.conexionDB = conexionDB;

        // Cargar los departamentos
        cargarDepartamentos(conexionDB);
    }

    public DAgregarEmpleado(Dashboard parent, boolean modal, Conexion conexionDB, Empleado empleadoEditar) {
        this(parent, modal, conexionDB); // llama al otro constructor
        this.empleadoEditar = empleadoEditar;
        precargarDatosEmpleado(empleadoEditar);
    }

    private void precargarDatosEmpleado(Empleado empleado) {
        txt_nombres.setText(empleado.getNombres());
        txt_apellidos.setText(empleado.getApellidos());
        txt_dni.setText(empleado.getDni());
        txt_correo_electronico.setText(empleado.getCorreoElectronico());
        txt_telefono.setText(empleado.getTelefono());
        dc_fecha_contratacion.setDate(empleado.getFechaContratacion());

        // Seleccionar el departamento en el combo
        for (int i = 0; i < cb_departamentos.getItemCount(); i++) {
            Departamento dep = cb_departamentos.getItemAt(i);
            if (dep.getIdDepartamento() == empleado.getIdDepartamento()) {
                cb_departamentos.setSelectedIndex(i);
                break;
            }
        }
    }

    private void cargarDepartamentos(Conexion conexionDB) {
        try {
            DepartamentoDAOImpl departamentoDAO = new DepartamentoDAOImpl(conexionDB.getConexion());
            List<Departamento> departamentos = departamentoDAO.obtenerTodosDepartamentos();

            cb_departamentos.removeAllItems(); // limpiar el combo
            for (Departamento dep : departamentos) {
                cb_departamentos.addItem(dep);
            }

        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error al cargar departamentos", ex);
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al cargar los departamentos",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIniciarSes = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txt_correo_electronico = new javax.swing.JTextField();
        btnAgregarEmpleado = new javax.swing.JButton();
        lblCorreo1 = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        lblCorreo2 = new javax.swing.JLabel();
        txt_dni = new javax.swing.JTextField();
        lblCorreo3 = new javax.swing.JLabel();
        btnLogin3 = new javax.swing.JButton();
        lblCorreo4 = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        lblCorreo5 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        lblCorreo6 = new javax.swing.JLabel();
        cb_departamentos = new javax.swing.JComboBox<>();
        dc_fecha_contratacion = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSes.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblIniciarSes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIniciarSes.setText("Agregar Empleado");
        lblIniciarSes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblIniciarSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 778, -1));

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo.setText("Nombres");
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 340, 39));

        txt_correo_electronico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_correo_electronico.setForeground(new java.awt.Color(27, 55, 79));
        txt_correo_electronico.setCaretColor(new java.awt.Color(27, 55, 79));
        txt_correo_electronico.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jPanel1.add(txt_correo_electronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 338, 43));

        btnAgregarEmpleado.setBackground(new java.awt.Color(0, 121, 216));
        btnAgregarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarEmpleado.setText("Agregar");
        btnAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 470, 230, 60));

        lblCorreo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo1.setText("Apellidos");
        jPanel1.add(lblCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 338, 39));

        txt_apellidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_apellidos.setForeground(new java.awt.Color(27, 55, 79));
        txt_apellidos.setCaretColor(new java.awt.Color(27, 55, 79));
        txt_apellidos.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jPanel1.add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 338, 43));

        lblCorreo2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo2.setText("DNI");
        jPanel1.add(lblCorreo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 338, 39));

        txt_dni.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_dni.setForeground(new java.awt.Color(27, 55, 79));
        txt_dni.setCaretColor(new java.awt.Color(27, 55, 79));
        txt_dni.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jPanel1.add(txt_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 338, 43));

        lblCorreo3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo3.setText("Fecha Contratación");
        jPanel1.add(lblCorreo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 338, 39));

        btnLogin3.setBackground(new java.awt.Color(255, 102, 102));
        btnLogin3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogin3.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin3.setText("Cancelar");
        btnLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 180, 60));

        lblCorreo4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo4.setText("Correo Electronico");
        jPanel1.add(lblCorreo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 184, 39));

        txt_nombres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_nombres.setForeground(new java.awt.Color(27, 55, 79));
        txt_nombres.setCaretColor(new java.awt.Color(27, 55, 79));
        txt_nombres.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jPanel1.add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 338, 43));

        lblCorreo5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo5.setText("Telefono");
        jPanel1.add(lblCorreo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 184, 39));

        txt_telefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(27, 55, 79));
        txt_telefono.setCaretColor(new java.awt.Color(27, 55, 79));
        txt_telefono.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 338, 43));

        lblCorreo6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo6.setText("Departamento");
        jPanel1.add(lblCorreo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 184, 39));

        cb_departamentos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(cb_departamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 340, 40));

        dc_fecha_contratacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(dc_fecha_contratacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 340, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 790, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoActionPerformed
        String nombres = txt_nombres.getText().trim();
        String apellidos = txt_apellidos.getText().trim();
        String dni = txt_dni.getText().trim();
        String correoElectronico = txt_correo_electronico.getText().trim();
        String telefono = txt_telefono.getText().trim();

        java.util.Date fechaUtil = dc_fecha_contratacion.getDate();
        java.sql.Date fechaContratacion = null;
        if (fechaUtil != null) {
            fechaContratacion = new java.sql.Date(fechaUtil.getTime());
        }

        Departamento departamentoSeleccionado = (Departamento) cb_departamentos.getSelectedItem();
        int idDepartamento = departamentoSeleccionado != null ? departamentoSeleccionado.getIdDepartamento() : -1;

        EmpleadoDAOImpl empleadoDAO = new EmpleadoDAOImpl(conexionDB.getConexion());

        try {
            if (empleadoEditar == null) {
                // === INSERTAR ===
                Empleado empleado = new Empleado(nombres, apellidos, dni, fechaContratacion, correoElectronico, telefono, idDepartamento);
                empleadoDAO.crearEmpleado(empleado);
                JOptionPane.showMessageDialog(this, "Empleado agregado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // === EDITAR ===
                empleadoEditar.setNombres(nombres);
                empleadoEditar.setApellidos(apellidos);
                empleadoEditar.setDni(dni);
                empleadoEditar.setFechaContratacion(fechaContratacion);
                empleadoEditar.setCorreoElectronico(correoElectronico);
                empleadoEditar.setTelefono(telefono);
                empleadoEditar.setIdDepartamento(idDepartamento);

                empleadoDAO.actualizarEmpleado(empleadoEditar);
                JOptionPane.showMessageDialog(this, "Empleado actualizado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }

            // Refrescar tabla del Dashboard
            if (dashboard != null) {
                dashboard.cargarEmpleadosEnTabla(new EmpleadoDAOImpl(conexionDB.getConexion()));
            }

            this.dispose();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar el empleado: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Error al guardar empleado", ex);
        }
    }//GEN-LAST:event_btnAgregarEmpleadoActionPerformed

    private void btnLogin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnLogin3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnLogin3;
    private javax.swing.JComboBox<Departamento> cb_departamentos;
    private com.toedter.calendar.JDateChooser dc_fecha_contratacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblCorreo2;
    private javax.swing.JLabel lblCorreo3;
    private javax.swing.JLabel lblCorreo4;
    private javax.swing.JLabel lblCorreo5;
    private javax.swing.JLabel lblCorreo6;
    private javax.swing.JLabel lblIniciarSes;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_correo_electronico;
    private javax.swing.JTextField txt_dni;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
